language: node_js
cache:
  directories:
  - ~/.npm
node_js:
  # https://medium.com/@mikeal/stop-supporting-old-releases-70cfa0e04b0c
  - 'lts/*'

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run test-coverage
      after_success: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
#    - stage: release
#      node_js: lts/*
#      deploy:
#        provider: script
#        skip_cleanup: true
#        script:
#          - npm run release